### ISSUE TITLE
Does this package work?

### ISSUE THREAD

**Issue by michaelofrancis** [pmamouris/ccoptimalmatch#1]
This package comes up high on Google searches for an R package to do case control matching, but I'm not even entirely sure if it works. There seems to be no associated citation or publication. Is this repository actively maintained or was this project discarded before finalization? 

Thanks.

**Comment by pmamouris** [comment]
Hi Michael,

This is an Rpackage. So, in the description of the Rpackage, namely here:
https://cran.r-project.org/web/packages/ccoptimalmatch/ccoptimalmatch.pdf

You can see the publication:
 Mamouris (2021) <doi:10.1186/s12874-021-01256-3> for an overview.

And also a tutorial accompanied:
https://cran.r-project.org/web/packages/ccoptimalmatch/vignettes/ccoptimalmatching_vignette.html

So, the project is quite complete already. Am I missing something? Do you mean that I should describe it better in the repository somewhere?

Thanks for asking and for your input!
